driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.8
  - name: centos-7.2
  - name: debian-7.11
  - name: debian-8.5
  - name: fedora-24
    run_list: yum::dnf_yum_compat
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
- name: default
  run_list:
  - recipe[haproxy::manual]
- name: lwrp
  run_list:
  - recipe[haproxy-test]
  attributes:
    haproxy:
      enable_default_http: false
      global_options: ['quiet']
      listeners:
        listen:
          lb_test:
            - balance roundrobin
            - bind 0.0.0.0:5000
            - maxconn 10
            - mode tcp
            - server netcat1 127.0.0.1:5001
            - server netcat2 127.0.0.1:5002
- name: app_lb
  run_list:
  - recipe[haproxy::app_lb]
